apiVersion: apps/v1
kind: Deployment
metadata:
  name: crawler-api
  labels:
    app: crawler-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: crawler-api
  template:
    metadata:
      labels:
        app: crawler-api
    spec:
      containers:
        - name: crawler-api
          image: your-docker-repo/my-crawler:latest
          ports:
            - containerPort: 8080
          env:
            - name: MONGO_URI
              valueFrom:
                secretKeyRef:
                  name: crawler-secrets
                  key: mongo-uri
          volumeMounts:
            - name: config-volume
              mountPath: /app/config
      volumes:
        - name: config-volume
          configMap:
            name: crawler-config
